[package]
name = "anchor-flashloan"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "anchor_flashloan"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []


[dependencies]

anchor-lang = { version = "=1.0.0-rc.2", features = ["init-if-needed"] }
anchor-spl = "=1.0.0-rc.2"
solana-instructions-sysvar = "3.0"
solana-sysvar-id = "3.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
